from __future__ import annotations

from typing import Any

ROOMS: list[dict[str, Any]] = [
    {
        "id": "deluxe-101",
        "name": "Deluxe City Room",
        "city": "Mumbai",
        "price": 4800,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Free Wi-Fi", "Breakfast", "City view", "Workspace"],
        "description": "A quiet upper-floor room with bright city views and fast access to business districts.",
    },
    {
        "id": "sea-102",
        "name": "Sea View Premium Room",
        "city": "Mumbai",
        "price": 6200,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Sea view", "Breakfast", "Smart TV", "Mini bar"],
        "description": "A bright premium room facing the coastline with warm interiors and a relaxed business desk.",
    },
    {
        "id": "heritage-103",
        "name": "Heritage Boutique Room",
        "city": "Mumbai",
        "price": 5400,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Heritage decor", "Breakfast", "Balcony", "Concierge"],
        "description": "A boutique room with heritage styling, perfect for guests who want a local stay experience.",
    },
    {
        "id": "business-104",
        "name": "Business Comfort Room",
        "city": "Mumbai",
        "price": 5100,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Workspace", "Fast Wi-Fi", "Laundry", "Breakfast"],
        "description": "A practical room for work trips with a larger desk, quiet floor access, and quick services.",
    },
    {
        "id": "suite-202",
        "name": "Executive Suite",
        "city": "Delhi",
        "price": 7200,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["King bed", "Airport pickup", "Lounge access", "Bathtub"],
        "description": "A large suite built for longer stays, with a separate living area and premium amenities.",
    },
    {
        "id": "capital-203",
        "name": "Capital Club Room",
        "city": "Delhi",
        "price": 6100,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Club lounge", "Airport desk", "Dinner buffet", "Workspace"],
        "description": "A club-level room with quick city access and a calm lounge for evening work or dining.",
    },
    {
        "id": "family-303",
        "name": "Family Garden Room",
        "city": "Bengaluru",
        "price": 5600,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Two queen beds", "Garden view", "Kids menu", "Pool access"],
        "description": "A comfortable room for families, close to the pool and breakfast lounge.",
    },
    {
        "id": "tech-304",
        "name": "Tech Park Studio",
        "city": "Bengaluru",
        "price": 4500,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Kitchenette", "Workspace", "Metro access", "Self check-in"],
        "description": "A compact studio near major tech parks with easy transport access and a kitchenette.",
    },
    {
        "id": "palace-401",
        "name": "Palace View Room",
        "city": "Jaipur",
        "price": 5900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Palace view", "Rooftop dining", "Breakfast", "Tour desk"],
        "description": "A warm room with palace-inspired interiors and rooftop access for city views.",
    },
    {
        "id": "lake-501",
        "name": "Lakefront Deluxe Room",
        "city": "Udaipur",
        "price": 6900,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Lake view", "Breakfast", "Boat desk", "Balcony"],
        "description": "A peaceful lakefront room with a private balcony and quick access to local sightseeing.",
    },
    {
        "id": "beach-601",
        "name": "Beach Resort Room",
        "city": "Goa",
        "price": 7600,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Beach access", "Pool", "Breakfast", "Bar"],
        "description": "A resort room with easy beach access, a pool, and bright coastal interiors.",
    },
    {
        "id": "colonial-602",
        "name": "Colonial Villa Room",
        "city": "Goa",
        "price": 8300,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Villa stay", "Garden", "Breakfast", "Scooter rental"],
        "description": "A villa-style room with old-world details, garden access, and slower holiday energy.",
    },
    {
        "id": "charminar-701",
        "name": "Charminar Comfort Room",
        "city": "Hyderabad",
        "price": 4300,
        "rating": 4.1,
        "image": "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Breakfast", "City tours", "Workspace", "Parking"],
        "description": "A comfortable city room with dependable essentials and quick access to local landmarks.",
    },
    {
        "id": "marina-801",
        "name": "Marina Bay Room",
        "city": "Chennai",
        "price": 4700,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Beach nearby", "Breakfast", "Workspace", "Gym"],
        "description": "A breezy room near the waterfront with work-friendly seating and simple modern styling.",
    },
    {
        "id": "hill-901",
        "name": "Hill View Retreat",
        "city": "Shimla",
        "price": 6800,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Hill view", "Heater", "Breakfast", "Bonfire"],
        "description": "A calm retreat with mountain views, warm interiors, and evening bonfire seating.",
    },
    {
        "id": "pune-1001",
        "name": "Koregaon Park Premium Room",
        "city": "Pune",
        "price": 5200,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Cafe district", "Breakfast", "Workspace", "Valet parking"],
        "description": "A polished room near Pune's dining streets with a quiet desk setup and quick city access.",
    },
    {
        "id": "pune-1002",
        "name": "Hinjewadi Business Studio",
        "city": "Pune",
        "price": 3900,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Kitchenette", "Fast Wi-Fi", "Laundry", "Self check-in"],
        "description": "A compact studio for tech-park stays with practical amenities for weekly work trips.",
    },
    {
        "id": "pune-1003",
        "name": "Baner Urban Suite",
        "city": "Pune",
        "price": 6100,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Suite layout", "Gym", "Breakfast", "City view"],
        "description": "A spacious suite in Baner with modern interiors, city views, and easy highway access.",
    },
    {
        "id": "pune-1004",
        "name": "Viman Nagar Airport Room",
        "city": "Pune",
        "price": 4700,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1551776235-dde6d482980b?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Airport transfer", "Breakfast", "Soundproofing", "Workspace"],
        "description": "A convenient airport-side room with soundproof windows and efficient check-in.",
    },
    {
        "id": "kochi-1101",
        "name": "Kochi Backwater Room",
        "city": "Kerala",
        "price": 6400,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1602002418082-dd4a1c6f8cbd?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Backwater view", "Breakfast", "Boat desk", "Balcony"],
        "description": "A relaxing Kerala room facing calm backwaters with a balcony and local breakfast service.",
    },
    {
        "id": "munnar-1102",
        "name": "Munnar Tea Estate Cottage",
        "city": "Kerala",
        "price": 7200,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Tea estate view", "Heater", "Breakfast", "Nature trail"],
        "description": "A hillside cottage surrounded by tea gardens, built for quiet leisure stays.",
    },
    {
        "id": "alleppey-1103",
        "name": "Alleppey Canal View Room",
        "city": "Kerala",
        "price": 5800,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Canal view", "Breakfast", "Houseboat booking", "Balcony"],
        "description": "A canal-facing room close to houseboat docks and peaceful evening walks.",
    },
    {
        "id": "kovalam-1104",
        "name": "Kovalam Beach Room",
        "city": "Kerala",
        "price": 6900,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Beach access", "Pool", "Breakfast", "Spa desk"],
        "description": "A beach-side Kerala room with resort services and relaxed coastal styling.",
    },
    {
        "id": "kolkata-1201",
        "name": "Park Street Heritage Room",
        "city": "Kolkata",
        "price": 4900,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Heritage decor", "Breakfast", "City tours", "Workspace"],
        "description": "A heritage-inspired room near central Kolkata's restaurants and cultural landmarks.",
    },
    {
        "id": "ahmedabad-1301",
        "name": "Riverfront Business Room",
        "city": "Ahmedabad",
        "price": 4600,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Riverfront nearby", "Breakfast", "Workspace", "Parking"],
        "description": "A business-friendly room with quick access to the riverfront and commercial districts.",
    },
    {
        "id": "lucknow-1401",
        "name": "Gomti Nagar Comfort Room",
        "city": "Lucknow",
        "price": 4200,
        "rating": 4.1,
        "image": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Breakfast", "Workspace", "Parking", "City tours"],
        "description": "A comfortable stay in Gomti Nagar with practical amenities and calm interiors.",
    },
    {
        "id": "mysuru-1501",
        "name": "Mysuru Palace Road Room",
        "city": "Mysuru",
        "price": 4400,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Palace nearby", "Breakfast", "Tour desk", "Balcony"],
        "description": "A relaxed room near palace attractions with a balcony and easy local transport.",
    },
    {
        "id": "coorg-1601",
        "name": "Coorg Coffee Estate Stay",
        "city": "Coorg",
        "price": 7400,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Coffee estate", "Breakfast", "Bonfire", "Nature trail"],
        "description": "A scenic estate stay with coffee plantation views and slow countryside mornings.",
    },
    {
        "id": "amritsar-1701",
        "name": "Golden Temple Comfort Room",
        "city": "Amritsar",
        "price": 4100,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Temple shuttle", "Breakfast", "Family room", "Parking"],
        "description": "A clean family-friendly room with shuttle support to major city landmarks.",
    },
    {
        "id": "varanasi-1801",
        "name": "Ghat View Heritage Room",
        "city": "Varanasi",
        "price": 5300,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80",
        "amenities": ["Ghat view", "Breakfast", "Walking tours", "Balcony"],
        "description": "A heritage room with old-city character and balcony views near the ghats.",
    },
]
